DROP TABLE IF EXISTS INC_PGM_DATA;
  
CREATE TABLE INC_PGM_DATA (
  PROGRAM_CODE VARCHAR(50) NOT NULL PRIMARY KEY,
  PROGRAM_NAME VARCHAR(250) NOT NULL,
  SCHEDULE_SERVICE VARCHAR(250) NOT NULL,
  STANDARD_SSP VARCHAR(250) NOT NULL,
  FREE_SSP VARCHAR(250) NOT NULL,
  FLEXI_SSP VARCHAR(250) NOT NULL,
  FLEXI_EW VARCHAR(250) NOT NULL
);