DROP TABLE IF EXISTS INC_PGM_DATA;
CREATE TABLE INC_PGM_DATA
(
   PROGRAM_CODE VARCHAR (10) NOT NULL PRIMARY KEY,
   PROGRAM_NAME VARCHAR (50) NOT NULL,
   DATE_FROM DATE NOT NULL,
   DATE_TO DATE NOT NULL
);
DROP TABLE IF EXISTS INC_PRD_STRUCTURE;
CREATE TABLE INC_PRD_STRUCTURE
(
   INC_STRUCTURE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   PROGRAM_CODE VARCHAR (10) NOT NULL,
   PROGRAM_NAME VARCHAR (50) NOT NULL,
   DATE_FROM DATE NOT NULL,
   DATE_TO DATE NOT NULL,
   PRODUCT_TYPE VARCHAR (50) NOT NULL,
   SUB_PRODUCT_TYPE VARCHAR (10) NOT NULL,
   PRODUCT_SALE_TYPE VARCHAR (50) NOT NULL,
   CONTRACT_TYPE VARCHAR (50) NOT NULL,
   RECIPIENT VARCHAR (50) NOT NULL,
   NO_OF_SERVICES INTEGER NOT NULL,
   PERFORMANCE_TARGET VARCHAR (50) NOT NULL,
   INCENTIVES INTEGER NOT NULL
);
DROP TABLE IF EXISTS INC_DLR_DETAILS;
CREATE TABLE INC_DLR_DETAILS
(
   DEALER_CODE VARCHAR (10) NOT NULL PRIMARY KEY,
   DEALER_NAME VARCHAR (100)
);
DROP TABLE IF EXISTS INC_DLR_PRD_TARGET;
CREATE TABLE INC_DLR_PRD_TARGET
(
   ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   DEALER_CODE VARCHAR (10),
   DEALER_NAME VARCHAR (100),
   SUB_PRD_TYPE_OSP VARCHAR (10),
   DEALER_TARGET_OSP INTEGER,
   SUB_PRD_TYPE_SSP VARCHAR (10),
   DEALER_TARGET_SSP INTEGER,
   DEALER_TARGET_MONTH VARCHAR (10)
);
DROP TABLE IF EXISTS INC_DLR_CONTRACT_SALES;
CREATE TABLE INC_DLR_CONTRACT_SALES
(
   ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   DEALER_CODE VARCHAR (10),
   DEALER_NAME VARCHAR (100),
   PRODUCT_TYPE VARCHAR (50),
   SUB_PRD_TYPE VARCHAR (10),
   NO_OF_CLAIMS_ALLOWED INTEGER,
   PRODUCT_SALE_TYPE VARCHAR (50),
   CONTRACT_TYPE VARCHAR (50),
   CONTRACT_STATUS VARCHAR (5),
   CONTRACT_REGISTRATION_DATE DATE
);
DROP TABLE IF EXISTS INC_DLR_CONTRACT_SALES_CANCELLATION;
CREATE TABLE INC_DLR_CONTRACT_SALES_CANCELLATION
(
   ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   DEALER_CODE VARCHAR (10),
   DEALER_NAME VARCHAR (100),
   PRODUCT_TYPE VARCHAR (50),
   SUB_PRD_TYPE VARCHAR (10),
   NO_OF_CLAIMS_ALLOWED INTEGER,
   PRODUCT_SALE_TYPE VARCHAR (50),
   CONTRACT_TYPE VARCHAR (50),
   CONTRACT_STATUS VARCHAR (5),
   CONTRACT_REGISTRATION_DATE DATE,
   CONTRACT_CANCELLATION_DATE DATE
);
DROP TABLE IF EXISTS INC_DLR_TOTAL_INCENTIVE;
CREATE TABLE INC_DLR_TOTAL_INCENTIVE
(
   ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
   DEALER_CODE VARCHAR (10),
   DEALER_NAME VARCHAR (100),
   PROGRAM_CODE VARCHAR (20),
   SUB_PRD_TYPE VARCHAR (10),
   NO_OF_CLAIMS_ALLOWED2 INT,
   NO_OF_CLAIMS_ALLOWED3 INT,
   NO_OF_CLAIMS_ALLOWED4 INT,
   NO_OF_CLAIMS_ALLOWED7 INT,
   TARGET_ACHIEVED INT,
   TARGET INT,
   ACHIEVED_PERCENTAGE INT,
   INCENTIVE_CATEGORY INT,
   TOTAL INT,
   DEALER_TARGET_MONTH VARCHAR (10)
);