DROP TABLE IF EXISTS INC_PGM_DATA;
  
CREATE TABLE INC_PGM_DATA (
  PROGRAM_CODE VARCHAR(50) NOT NULL PRIMARY KEY,
  PROGRAM_NAME VARCHAR(250) NOT NULL,
  DATE_FROM DATE NOT NULL,
  DATE_TO DATE NOT NULL
);

DROP TABLE IF EXISTS INC_PRD_STRUCTURE;
  
CREATE TABLE INC_PRD_STRUCTURE (
  INC_STRUCTURE_ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PROGRAM_CODE VARCHAR(50) NOT NULL,
  PROGRAM_NAME VARCHAR(250) NOT NULL,
  DATE_FROM DATE NOT NULL,
  DATE_TO DATE NOT NULL,  
  PRODUCT_TYPE VARCHAR(250) NOT NULL,
  SUB_PRODUCT_TYPE VARCHAR(250) NOT NULL,
  PRODUCT_SALE_TYPE VARCHAR(250) NOT NULL,
  SERVICE_TYPE VARCHAR(250) NOT NULL,
  RECEPIENT VARCHAR(250) NOT NULL,
  NO_OF_SERVICES INT NOT NULL,
  PERFORMANCE_TARGET VARCHAR(250) NOT NULL,
  INCENTIVES INT NOT NULL
);